name: thesis_project
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.2.0
  - torchvision=0.17.0
  - numpy=1.26.4
  - pillow=9.5.0
  - scikit-learn=1.3.2
  - matplotlib=3.8.3
  # - cudatoolkit=11.8
  - tqdm=4.66.2
  - notebook=6.5.4
  - pip
  - pip:
      - segmentation-models-pytorch==0.3.3
      - timm==0.9.2
      - ultralytics>=8.0.0
      - scikit-image==0.21.0
